[package]
name = "breakout"
version = "0.1.0"
edition = "2021"

[dependencies]
arduino_breakout_common = { path = "../../common/arduino_breakout_common" }
atsamd21g = { version = "0.12", features = ["rt"] }
cortex-m = { version = "0.7" }
cortex-m-rt = { version = "0.7" }
